# Generated by Django 3.2.19 on 2023-05-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('PhoneNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('TimeslotID', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('TableID', models.AutoField(primary_key=True, serialize=False)),
                ('TableNum', models.IntegerField()),
                ('MaxCapacity', models.IntegerField()),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('ReservationID', models.AutoField(primary_key=True, serialize=False)),
                ('NumOfGuests', models.IntegerField()),
                ('ReservationDate', models.DateField()),
                ('ReservationTime', models.TimeField()),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.restaurants')),
                ('TableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tables')),
                ('TimeslotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.timeslots')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.users')),
            ],
        ),
    ]
