# Generated by Django 3.2.19 on 2023-05-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='ReservationTime',
        ),
    ]
