# Generated by Django 3.2.19 on 2023-05-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservations_reservationtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='TableID',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
